server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/purchaseTicket
    username: root
    password: Autumn@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create